-- a)
CREATE DATABASE QLSVNhom;
GO

USE QLSVNhom;
GO

-- b)
-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV NVARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP NVARCHAR(200),
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL
);
GO

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(MAX),
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL,
    PUBKEY VARCHAR(20)
);
GO

-- Tạo bảng LOP
CREATE TABLE LOP (
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20),
    MASV VARCHAR(20),
    MAHP VARCHAR(20)
);
GO

-- Tạo bảng HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR(20) PRIMARY KEY,
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT
);
GO

-- Tạo bảng BANGDIEM
CREATE TABLE BANGDIEM (
    MASV NVARCHAR(20),
    MAHP VARCHAR(20),
    DIEMTHI VARBINARY(MAX),
    PRIMARY KEY (MASV, MAHP)
);
GO

-- TEST 
EXEC SP_INS_PUBLIC_NHANVIEN 
  @MANV='NV01', @HOTEN=N'Nguyễn Văn A', @EMAIL='nva@fit.edu',
  @LUONGCB=3000000, @TENDN=N'nva', @MK=N'abcd12';

SELECT * FROM NHANVIEN

EXEC SP_SEL_PUBLIC_NHANVIEN
  @TENDN = N'nva',
  @MK    = N'abcd12';


--DELETE FROM NHANVIEN WHERE TENDN = N'nva'